import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const tools = [
  {
    name: "ChatGPT Team",
    company: "OpenAI",
    logoEmoji: "💬",
    websiteUrl: "https://openai.com/chatgpt/team",
    description: "汎用AIアシスタント。文章作成・要約・翻訳・コード生成など幅広い業務に対応。チーム利用向けプランで会話履歴や管理機能を提供。",
    features: JSON.stringify([
      "メール・文書の下書き・校正",
      "データ分析・レポート作成",
      "社内FAQボットの構築",
      "SNS投稿文の生成",
      "多言語翻訳",
      "GPT-4oによる画像・音声入力対応",
    ]),
    categories: JSON.stringify(["chatbot", "email", "docs", "sns"]),
    automationTags: JSON.stringify(["メール", "文章作成", "要約", "翻訳", "SNS", "チャットボット", "FAQ", "レポート"]),
    freePlanAvailable: false,
    setupCost: "無料",
    monthlyPricePerUser: 3600,
    monthlyPriceLabel: "¥3,600/ユーザー（約$25）",
    enterpriseNote: "Enterprise プランは要問合せ",
    difficultyScore: 2,
    maintenanceScore: 1,
    requiredSkills: "管理者設定のみ（プログラミング不要）",
    costReductionPct: 20,
    timeReductionPct: 35,
    effectDescription: "文書作成・メール返信の時間を平均35%削減。月10時間の作業を約6.5時間に短縮する事例が多い。",
    effectBaseline: "削減率は導入前の同業務の作業時間（時間削減）・人件費（コスト削減）を基準に、各ベンダー公表値・ユーザー事例から算出した目安値です。",
    selfSetupNote: "管理者設定のみで対応可（約2時間、費用なし）",
    fullDelegationNote: "外部コンサルへの導入支援依頼で¥30,000〜¥100,000程度",
    selfMaintenanceNote: "ツール側で自動更新のため管理作業はほぼ不要（月0〜1時間程度）",
    fullMaintenanceNote: "運用サポート外注で¥10,000〜¥30,000/月程度",
    selfMaintenanceHoursPerMonth: 1,
    fullMaintenanceCostPerMonth: 30000,
    adminUserNote: "設定・管理担当者：¥3,600/ユーザー（チームプランライセンス）",
    endUserNote: "質問・利用するユーザー全員にライセンスが必要（¥3,600/ユーザー）。社員全員に配布する場合は人数分の費用が発生",
    endUserRequiresLicense: true,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack", "notion", "salesforce"]),
  },
  {
    name: "Microsoft Copilot 365",
    company: "Microsoft",
    logoEmoji: "🪟",
    websiteUrl: "https://www.microsoft.com/ja-jp/microsoft-365/copilot",
    description: "Word・Excel・Outlook・Teamsに直接統合されたAIアシスタント。既存のMicrosoft 365環境をそのまま活用してAIを導入できる。",
    features: JSON.stringify([
      "Outlookでのメール自動作成・要約",
      "Wordでの文書・レポート作成",
      "Excelでのデータ分析・グラフ生成",
      "Teams会議の自動議事録作成",
      "PowerPointプレゼン自動生成",
      "SharePointを活用した社内知識検索",
    ]),
    categories: JSON.stringify(["chatbot", "email", "docs"]),
    automationTags: JSON.stringify(["メール", "文書作成", "Excel", "議事録", "プレゼン", "Microsoft", "Teams", "Outlook"]),
    freePlanAvailable: false,
    setupCost: "無料（Microsoft 365契約が必要）",
    monthlyPricePerUser: 4400,
    monthlyPriceLabel: "¥4,400/ユーザー（約$30）",
    enterpriseNote: "Microsoft 365 E3/E5との組み合わせ推奨",
    difficultyScore: 2,
    maintenanceScore: 2,
    requiredSkills: "Microsoft 365管理者設定（IT管理者推奨）",
    costReductionPct: 25,
    timeReductionPct: 40,
    effectDescription: "Microsoft社調査では週平均4.4時間の時間節約を報告。メール処理・文書作成業務での効果が特に大きい。",
    effectBaseline: "Microsoft社「Work Trend Index」2024年調査に基づく。週40時間勤務の従業員を対象とした時間削減実績値。コスト削減率は人件費を基準として算出。",
    selfSetupNote: "Microsoft 365管理コンソールで設定可（IT管理者なら社内対応可）",
    fullDelegationNote: "IT担当者またはSIerへの導入支援依頼で¥50,000〜¥200,000程度",
    selfMaintenanceNote: "Microsoft 365管理者による月次確認（月1〜2時間程度）",
    fullMaintenanceNote: "IT管理者外注で¥20,000〜¥50,000/月程度",
    selfMaintenanceHoursPerMonth: 2,
    fullMaintenanceCostPerMonth: 50000,
    adminUserNote: "設定・管理担当者：¥4,400/ユーザー（M365 Copilotライセンス）",
    endUserNote: "AI機能を使うユーザー全員にライセンスが必要（¥4,400/ユーザー）。閲覧・編集のみなら既存M365ライセンスで可",
    endUserRequiresLicense: true,
    relatedBaseEnv: "microsoft",
    compatibleEnvs: JSON.stringify(["microsoft"]),
  },
  {
    name: "Google Workspace（Gemini）",
    company: "Google",
    logoEmoji: "🔵",
    websiteUrl: "https://workspace.google.com/intl/ja/",
    description: "Gmail・Docs・Sheets・SlidesにGemini AIが統合。Google Workspaceユーザーは追加コストなしで利用できるプランもあり。",
    features: JSON.stringify([
      "Gmailでのメール自動返信・要約",
      "Google Docsでの文書作成・校正",
      "Google Sheetsでのデータ分析",
      "Google Slidesでのプレゼン自動生成",
      "Google Meetの議事録・要約",
      "NotebookLMでの社内文書ナレッジ化",
    ]),
    categories: JSON.stringify(["chatbot", "email", "docs"]),
    automationTags: JSON.stringify(["メール", "Gmail", "文書作成", "スプレッドシート", "プレゼン", "議事録", "Google"]),
    freePlanAvailable: false,
    setupCost: "Gemini AI機能の追加費用は無料。Google Workspace契約が必要（¥1,700〜/ユーザー/月、Business Starter〜）",
    monthlyPricePerUser: 1700,
    monthlyPriceLabel: "¥1,700〜/ユーザー（Business Starter〜）",
    enterpriseNote: "Gemini Advanced は別途 ¥2,900/ユーザー",
    difficultyScore: 1,
    maintenanceScore: 1,
    requiredSkills: "Google 管理コンソールの基本設定（プログラミング不要）",
    costReductionPct: 20,
    timeReductionPct: 30,
    effectDescription: "Google Workspace既存ユーザーは追加投資ほぼゼロで導入可能。メール・文書作成で月あたり平均20〜30%の時間削減。",
    effectBaseline: "Google/IDC共同調査（2024年）に基づく。メール・文書作成業務の合計時間・人件費コストを基準値として算出。",
    selfSetupNote: "管理コンソールで有効化するだけ（30分程度、費用なし）",
    fullDelegationNote: "外部パートナーへの導入支援・研修依頼で¥30,000〜¥100,000程度",
    selfMaintenanceNote: "ほぼ自動更新のため技術的管理は最小限。ただしAIに参照させる情報の範囲・アクセス権限の確認、機密情報の除外管理が別途必要（月2〜4時間程度）",
    fullMaintenanceNote: "外部サポート契約で¥10,000〜¥30,000/月程度",
    selfMaintenanceHoursPerMonth: 4,
    fullMaintenanceCostPerMonth: 30000,
    adminUserNote: "設定・管理担当者：¥1,700〜/ユーザー（Workspace契約、Gemini Advanced は+¥2,900/ユーザー）",
    endUserNote: "AI機能を使うユーザー全員にWorkspaceライセンスが必要（¥1,700〜/ユーザー）。Gemini Advanced利用は追加費用あり",
    endUserRequiresLicense: true,
    isIncludedInEnv: "google",
    relatedBaseEnv: "google",
    compatibleEnvs: JSON.stringify(["google", "slack", "notion"]),
  },
  {
    name: "Notion AI",
    company: "Notion Labs",
    logoEmoji: "📝",
    websiteUrl: "https://www.notion.com/ja/product/ai",
    description: "ドキュメント・wiki・プロジェクト管理ツールNotionに統合されたAI。社内ナレッジベースの構築・検索・要約に特化。",
    features: JSON.stringify([
      "社内ドキュメント・マニュアルのAI検索",
      "議事録・レポートの自動要約",
      "ドキュメントのAI生成・改善提案",
      "データベースの自動入力・整理",
      "Q&A型チャットボットの構築",
      "チーム向けナレッジベース管理",
    ]),
    categories: JSON.stringify(["chatbot", "docs"]),
    automationTags: JSON.stringify(["ナレッジ", "チャットボット", "FAQ", "議事録", "文書作成", "wiki", "社内検索"]),
    freePlanAvailable: false,
    setupCost: "無料",
    monthlyPricePerUser: 1650,
    monthlyPriceLabel: "¥1,650/ユーザー（Notion AI アドオン）",
    difficultyScore: 1,
    maintenanceScore: 1,
    requiredSkills: "プログラミング不要・誰でも設定可",
    costReductionPct: 15,
    timeReductionPct: 25,
    effectDescription: "情報検索・ドキュメント作成時間を約25%削減。社内ナレッジの属人化を防ぎ、新人教育コストの削減に貢献。",
    effectBaseline: "Notionユーザー調査（2023〜2024年）に基づく。情報検索・文書作成業務の所要時間・関連人件費を基準として算出。",
    selfSetupNote: "プランのアップグレードで即利用開始（費用なし）",
    fullDelegationNote: "ナレッジ設計・初期構築を外部コンサルへ依頼で¥30,000〜¥80,000程度",
    selfMaintenanceNote: "社内ナレッジ・ドキュメントの追加・更新に加え、AIに参照させてよい情報の範囲確認・機密ページのアクセス権限管理が必要（月3〜6時間程度）",
    fullMaintenanceNote: "ナレッジ管理の外部委託で¥20,000〜¥50,000/月程度",
    selfMaintenanceHoursPerMonth: 6,
    fullMaintenanceCostPerMonth: 50000,
    adminUserNote: "ナレッジ管理・編集担当者：¥1,650/ユーザー（Notion AI アドオン）",
    endUserNote: "社内ユーザーがNotionに直接ログインして使う場合は人数分ライセンス必要。社外や広範囲に公開する場合はDify等の連携システムが別途必要（Dify Professional ¥4,800/月〜）",
    endUserRequiresLicense: true,
    relatedBaseEnv: "notion",
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack"]),
  },
  {
    name: "Slack AI",
    company: "Salesforce（Slack）",
    logoEmoji: "💜",
    websiteUrl: "https://slack.com/intl/ja-jp/features/ai",
    description: "Slack上の会話・ドキュメントをAIが要約・検索。チャンネルの長い会話を瞬時にキャッチアップできる社内コミュニケーション特化AI。",
    features: JSON.stringify([
      "チャンネルの会話・スレッドの自動要約",
      "過去のSlack会話を横断検索",
      "Slack Canvasのドキュメント作成支援",
      "ハドルの議事録・要約",
      "ワークフロービルダーでの業務自動化",
    ]),
    categories: JSON.stringify(["chatbot", "docs"]),
    automationTags: JSON.stringify(["Slack", "要約", "社内検索", "ナレッジ", "議事録", "コミュニケーション"]),
    freePlanAvailable: false,
    setupCost: "無料（Slackプロプラン以上が必要）",
    monthlyPricePerUser: 1300,
    monthlyPriceLabel: "¥1,300/ユーザー（Slack AIアドオン）",
    difficultyScore: 1,
    maintenanceScore: 1,
    requiredSkills: "Slack管理者設定のみ（プログラミング不要）",
    costReductionPct: 15,
    timeReductionPct: 30,
    effectDescription: "情報収集・会議の振り返りにかかる時間を30%削減。長いスレッドの読み返し時間がほぼゼロになる効果あり。",
    effectBaseline: "Slack社の2024年ユーザー調査に基づく。情報収集・会議振り返りに費やす時間・関連コストを基準として算出。",
    selfSetupNote: "Slack管理コンソールで有効化（15分程度、費用なし）",
    fullDelegationNote: "Slack公式パートナーへの社内展開支援依頼で¥50,000〜¥150,000程度",
    selfMaintenanceNote: "ほぼ自動更新のため管理作業は最小限（月0〜1時間程度）",
    fullMaintenanceNote: "Slackパートナーの保守契約で¥10,000〜¥30,000/月程度",
    selfMaintenanceHoursPerMonth: 1,
    fullMaintenanceCostPerMonth: 30000,
    adminUserNote: "管理者・設定担当者：Slack Pro以上＋¥1,300/ユーザー（Slack AI アドオン）",
    endUserNote: "Slack上で回答を受け取るユーザー全員にSlackアカウントが必要（Slackプランの人数分料金が別途発生）",
    endUserRequiresLicense: true,
    relatedBaseEnv: "slack",
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack", "notion", "salesforce"]),
  },
  {
    name: "Jasper AI",
    company: "Jasper",
    logoEmoji: "✨",
    websiteUrl: "https://www.jasper.ai",
    description: "マーケティング・コンテンツ作成に特化したAI。ブランドトーンを学習して一貫したSNS投稿・ブログ・広告文を自動生成。",
    features: JSON.stringify([
      "SNS投稿文の一括生成（Instagram/X/LinkedIn等）",
      "ブログ記事・コラムの自動作成",
      "広告コピー・LP文章の生成",
      "ブランドガイドラインに沿ったトーン統一",
      "多言語コンテンツ生成",
      "A/Bテスト用バリエーション生成",
    ]),
    categories: JSON.stringify(["sns", "docs"]),
    automationTags: JSON.stringify(["SNS", "ブログ", "マーケティング", "広告", "コンテンツ", "Instagram", "X", "コピーライティング"]),
    freePlanAvailable: false,
    setupCost: "無料",
    monthlyPricePerUser: 5600,
    monthlyPriceLabel: "¥5,600/ユーザー（約$39、Creator）",
    enterpriseNote: "Businessプランは要問合せ",
    difficultyScore: 2,
    maintenanceScore: 1,
    requiredSkills: "管理者設定のみ（マーケ担当者が直接利用可）",
    costReductionPct: 30,
    timeReductionPct: 50,
    effectDescription: "SNS・ブログ投稿作成時間を最大50%削減。外部ライター費用の削減や内製化にも貢献。",
    effectBaseline: "Jasper社ユーザー事例に基づく。外部ライター・担当者がSNS・ブログ投稿を作成するのにかかる時間・外注費用を基準として算出。",
    selfSetupNote: "アカウント作成・メンバー招待のみ（費用なし）",
    fullDelegationNote: "コンテンツ戦略・ブランドガイドライン設計込みの外部依頼で¥100,000〜¥300,000程度",
    selfMaintenanceNote: "コンテンツ方針・ブランドトーンの見直し、プロンプト調整（月1〜3時間程度）",
    fullMaintenanceNote: "コンテンツ戦略の外部委託で¥50,000〜¥150,000/月程度",
    selfMaintenanceHoursPerMonth: 3,
    fullMaintenanceCostPerMonth: 150000,
    adminUserNote: "コンテンツ作成・管理担当者：¥5,600/ユーザー（Creatorプラン）",
    endUserNote: "Jasperで生成したSNS投稿・記事の閲覧者（一般ユーザー）は費用なし。コンテンツを直接作成・編集するメンバーのみライセンスが必要",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack"]),
  },
  {
    name: "Dify",
    company: "Dify.AI",
    logoEmoji: "🔧",
    websiteUrl: "https://dify.ai",
    description: "社内向けAIアプリ・チャットボットをノーコードで構築できるプラットフォーム。自社データを学習させたカスタムAIを作成できる。",
    features: JSON.stringify([
      "社内ドキュメントを学習したカスタムチャットボット",
      "社内ナレッジに基づくQ&A自動応答",
      "PDF・Word・Excelなどの資料を学習",
      "複数AIモデルの切り替え（GPT/Claude等）",
      "APIで既存システムと連携",
      "クラウド版・オンプレミス版選択可",
    ]),
    categories: JSON.stringify(["chatbot"]),
    automationTags: JSON.stringify(["チャットボット", "ナレッジ", "FAQ", "社内検索", "カスタムAI", "自社データ", "RAG"]),
    freePlanAvailable: true,
    freePlanDescription: "クラウド版無料プランあり（月200メッセージまで）",
    setupCost: "無料〜（クラウド版）/ 自社サーバー代（オンプレ）",
    monthlyPriceFlat: 4800,
    monthlyPriceLabel: "無料〜¥4,800/月（Professional）",
    enterpriseNote: "オンプレミス版・大規模利用は要問合せ",
    difficultyScore: 3,
    maintenanceScore: 3,
    requiredSkills: "API設定・データ整備が必要（IT担当者または外部支援推奨）",
    costReductionPct: 40,
    timeReductionPct: 50,
    effectDescription: "社内問い合わせ対応時間を最大50%削減。FAQやマニュアル問い合わせを自動化することで人的コストを大幅削減。",
    effectBaseline: "Dify導入事例に基づく。AI導入前の問い合わせ対応・FAQサポートにかかる人件費・時間を基準として算出。",
    selfSetupNote: "プログラミングが必要なため外注推奨。外注費用の目安：¥100,000〜¥300,000程度（要件・規模による）",
    fullDelegationNote: "要件定義・構築・テスト・運用設計まで全て外注で¥300,000〜¥800,000程度",
    selfMaintenanceNote: "学習データの追加・更新・モデル調整に加え、AIに参照させてよい情報の範囲確認・機密情報の除外管理が必要（月5〜10時間程度）",
    fullMaintenanceNote: "外部保守契約で¥50,000〜¥150,000/月程度",
    selfMaintenanceHoursPerMonth: 10,
    fullMaintenanceCostPerMonth: 150000,
    adminUserNote: "チャットボット構築・管理担当者：プランに含まれる（Professional ¥4,800/月の固定費）",
    endUserNote: "チャットボットに質問するユーザー：プランのメッセージ数内であれば追加費用なし。Dify自体はユーザー数課金なし",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack", "notion", "salesforce"]),
  },
  {
    name: "HubSpot（AI機能）",
    company: "HubSpot",
    logoEmoji: "🟠",
    websiteUrl: "https://www.hubspot.com/artificial-intelligence",
    description: "CRM・営業・マーケティング管理ツールにAIを統合。メール自動作成・リード分析・顧客対応の自動化を一元管理。",
    features: JSON.stringify([
      "営業メールの自動生成・パーソナライズ",
      "顧客問い合わせへのAI自動返信（チャット）",
      "リードスコアリングの自動化",
      "コンテンツ・ブログのAI作成支援",
      "Eメールキャンペーンの最適化提案",
    ]),
    categories: JSON.stringify(["email", "chatbot", "sns"]),
    automationTags: JSON.stringify(["メール", "営業", "CRM", "顧客対応", "マーケティング", "自動返信", "リード"]),
    freePlanAvailable: true,
    freePlanDescription: "無料CRMプランでAI機能の一部を利用可",
    setupCost: "無料〜（プランにより変動）",
    monthlyPriceFlat: 5400,
    monthlyPriceLabel: "¥5,400/月〜（Starter）",
    enterpriseNote: "Professional / Enterprise は ¥90,000/月〜",
    difficultyScore: 3,
    maintenanceScore: 2,
    requiredSkills: "管理者設定＋初期CRM設計（IT知識あると尚良）",
    costReductionPct: 25,
    timeReductionPct: 35,
    effectDescription: "営業メール作成・顧客対応時間を35%削減。リードナーチャリングの自動化でコンバージョン率改善も期待できる。",
    effectBaseline: "HubSpot社の2024年調査・導入事例に基づく。メール作成・顧客対応にかかる工数・外注費用を基準として算出。",
    selfSetupNote: "基本設定は自社可。CRM設計・カスタマイズの外注費用の目安：¥100,000〜¥300,000程度",
    fullDelegationNote: "HubSpotパートナーへの全導入・定着支援依頼で¥300,000〜¥1,000,000程度",
    selfMaintenanceNote: "CRM担当者によるデータ整備・設定更新（月2〜5時間）",
    fullMaintenanceNote: "HubSpotパートナーの保守契約で¥30,000〜¥100,000/月程度",
    selfMaintenanceHoursPerMonth: 5,
    fullMaintenanceCostPerMonth: 100000,
    adminUserNote: "CRM管理・設定担当者：¥5,400/月〜（Starterは固定費）",
    endUserNote: "チャットウィジェット経由で問い合わせるエンドユーザー（顧客・社員）：費用なし。HubSpotのプラン内で対応可能",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack"]),
  },
  {
    name: "Salesforce Einstein",
    company: "Salesforce",
    logoEmoji: "☁️",
    websiteUrl: "https://www.salesforce.com/jp/artificial-intelligence/",
    description: "Salesforce CRMに統合されたエンタープライズ向けAI。大規模な顧客対応・営業・サポート業務の自動化に対応。",
    features: JSON.stringify([
      "顧客メール・ケースの自動分類・返信",
      "営業予測・リードスコアリング",
      "カスタマーサポートの自動応答",
      "サービスクラウドでのFAQ自動応答",
      "Agentforce による完全自律型AI対応",
    ]),
    categories: JSON.stringify(["email", "chatbot"]),
    automationTags: JSON.stringify(["営業", "CRM", "Salesforce", "顧客対応", "メール", "サポート", "エンタープライズ"]),
    freePlanAvailable: false,
    setupCost: "要問合せ（導入支援費用が別途必要）",
    monthlyPricePerUser: 30000,
    monthlyPriceLabel: "¥30,000〜/ユーザー（概算）",
    enterpriseNote: "大企業向け。初期導入費・カスタマイズ費が別途必要",
    difficultyScore: 5,
    maintenanceScore: 4,
    requiredSkills: "Salesforce認定管理者またはシステムインテグレーターが必要",
    costReductionPct: 35,
    timeReductionPct: 40,
    effectDescription: "大規模な顧客対応・営業プロセスで最大40%の工数削減。ROI実現まで6〜12ヶ月が目安。",
    effectBaseline: "Salesforce社「State of CRM」2024年調査に基づく。AI導入前の顧客対応・営業工数・人件費を基準として算出。",
    selfSetupNote: "自社単独での導入は困難。認定SIerへの依頼が必須（¥500,000〜が目安）",
    fullDelegationNote: "大手SIer経由での構築・カスタマイズ・保守で¥1,000,000〜¥5,000,000程度（規模により大幅変動）",
    selfMaintenanceNote: "認定管理者による定期メンテナンスが必須（月10〜20時間）",
    fullMaintenanceNote: "SIerの保守契約で¥100,000〜¥300,000/月程度",
    selfMaintenanceHoursPerMonth: 20,
    fullMaintenanceCostPerMonth: 300000,
    adminUserNote: "Salesforce管理者・設定担当者：¥30,000〜/ユーザー（ライセンス込み）",
    endUserNote: "Service Cloud等のチャットや電話で問い合わせるエンドユーザー：費用なし。ただし対応する社内オペレーターにはライセンスが必要（¥30,000〜/ユーザー）",
    endUserRequiresLicense: false,
    relatedBaseEnv: "salesforce",
    compatibleEnvs: JSON.stringify(["salesforce", "slack", "microsoft"]),
  },
  {
    name: "Buffer（AI アシスタント）",
    company: "Buffer",
    logoEmoji: "📱",
    websiteUrl: "https://buffer.com",
    description: "SNS管理ツールにAIが統合。Instagram・X・Facebook・LinkedInなど複数のSNSへの投稿を一元管理・自動生成。",
    features: JSON.stringify([
      "SNS投稿文のAI自動生成（複数媒体対応）",
      "最適な投稿時間の分析・予約投稿",
      "ハッシュタグの自動提案",
      "エンゲージメント分析レポート",
      "コンテンツカレンダーの管理",
    ]),
    categories: JSON.stringify(["sns"]),
    automationTags: JSON.stringify(["SNS", "Instagram", "X", "Facebook", "LinkedIn", "投稿", "スケジュール", "ハッシュタグ"]),
    freePlanAvailable: true,
    freePlanDescription: "無料プランあり（3チャンネルまで）",
    setupCost: "無料",
    monthlyPriceFlat: 1500,
    monthlyPriceLabel: "無料〜¥1,500/月（Essentials）",
    difficultyScore: 1,
    maintenanceScore: 1,
    requiredSkills: "プログラミング不要・誰でも設定可（SNS担当者が直接利用）",
    costReductionPct: 20,
    timeReductionPct: 45,
    effectDescription: "SNS投稿作成・管理時間を最大45%削減。複数SNSの一括管理でコンテンツ担当者の負担を大幅軽減。",
    effectBaseline: "Buffer社ユーザー事例に基づく。複数SNSへの手動投稿・コンテンツ作成にかかる時間・コンテンツ制作費用を基準として算出。",
    selfSetupNote: "SNSアカウントを連携するだけ（10〜15分、費用なし）",
    fullDelegationNote: "SNSマーケ会社への運用全面委託で¥50,000〜¥200,000/月程度（コンテンツ制作込み）",
    selfMaintenanceNote: "投稿内容の確認・スケジュール調整を社内担当者が対応（月2〜5時間程度）",
    fullMaintenanceNote: "SNS運用外注で¥50,000〜¥200,000/月程度（コンテンツ込み）",
    selfMaintenanceHoursPerMonth: 5,
    fullMaintenanceCostPerMonth: 200000,
    adminUserNote: "SNS管理・投稿担当者：¥1,500/月〜（Essentialsプラン固定費）",
    endUserNote: "SNSフォロワー・閲覧者（一般ユーザー）：費用なし。Bufferで作成・投稿したコンテンツは各SNSで誰でも閲覧可能",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google", "slack"]),
  },
  {
    name: "NotebookLM",
    company: "Google",
    logoEmoji: "📓",
    websiteUrl: "https://notebooklm.google.com",
    description: "PDFや文書、スライドをアップロードするだけで、AIがその内容を完全に理解し、Q&A・要約・ポッドキャスト自動生成ができるGoogle製ナレッジAI。社内文書の活用に最適。",
    features: JSON.stringify([
      "PDF・Word・スライドを学習してQ&A対応",
      "複数文書を横断した情報検索・比較",
      "議事録・レポートの自動要約",
      "音声ポッドキャスト形式での内容解説生成",
      "学習ガイド・FAQ自動生成",
      "Google ドライブと直接連携",
    ]),
    categories: JSON.stringify(["chatbot", "docs"]),
    automationTags: JSON.stringify(["ナレッジ", "PDF", "文書解析", "社内検索", "要約", "FAQ", "Google", "資料分析"]),
    freePlanAvailable: true,
    freePlanDescription: "現在無料で提供中（Google アカウントで利用可）",
    setupCost: "無料",
    monthlyPriceFlat: 0,
    monthlyPriceLabel: "無料（Google アカウントで利用可）",
    enterpriseNote: "Google Workspace Business プランで拡張機能利用可",
    difficultyScore: 1,
    maintenanceScore: 1,
    requiredSkills: "プログラミング不要・誰でも設定可（ファイルをアップロードするだけ）",
    costReductionPct: 30,
    timeReductionPct: 50,
    effectDescription: "社内文書の検索・読み込み時間を最大50%削減。大量の資料を担当者が読む代わりにAIが要約・回答することで、意思決定スピードが向上。",
    effectBaseline: "Google発表の事例・ユーザーレポートに基づく。文書を手動で読み込み・検索する時間・外部リサーチ費用を基準として算出。",
    selfSetupNote: "ファイルをアップロードするだけで即利用開始（費用なし）",
    fullDelegationNote: "社内展開・活用研修・ナレッジ整備の外部支援依頼で¥30,000〜¥100,000程度",
    selfMaintenanceNote: "参照資料の追加・更新に加え、AIに読み込ませてよい情報かどうかの確認・機密文書の除外管理が必要（月2〜4時間程度）",
    fullMaintenanceNote: "ナレッジ管理の外部委託で¥20,000〜¥50,000/月程度",
    selfMaintenanceHoursPerMonth: 4,
    fullMaintenanceCostPerMonth: 50000,
    adminUserNote: "文書管理・ナレッジ構築担当者：現在無料（Googleアカウントのみ）",
    endUserNote: "質問・閲覧ユーザー：現在無料（Googleアカウントが必要）。社外ユーザーへの公開は現状制限があり、社内利用が前提",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google"]),
  },
  {
    name: "Genspark",
    company: "Genspark",
    logoEmoji: "⚡",
    websiteUrl: "https://www.genspark.ai",
    description: "AIがWeb上の最新情報をリアルタイム調査し、複数情報源を統合して資料・レポート・スライドを自動生成するAIリサーチエージェント。市場調査・競合分析・提案資料作成に威力を発揮。",
    features: JSON.stringify([
      "市場調査・競合分析レポートの自動生成",
      "複数Webソースを横断した情報収集・統合",
      "プレゼンスライドの自動作成",
      "最新ニュース・トレンドの要約レポート",
      "SNS投稿・ブログ記事の自動生成",
      "マルチモーダル対応（画像・動画検索含む）",
    ]),
    categories: JSON.stringify(["docs", "sns"]),
    automationTags: JSON.stringify(["リサーチ", "市場調査", "競合分析", "プレゼン", "レポート", "SNS", "資料作成", "Web検索"]),
    freePlanAvailable: true,
    freePlanDescription: "無料プランあり（利用回数制限あり）",
    setupCost: "無料",
    monthlyPriceFlat: 0,
    monthlyPriceLabel: "無料〜（有料プランは要確認）",
    enterpriseNote: "エンタープライズプランは要問合せ",
    difficultyScore: 1,
    maintenanceScore: 1,
    requiredSkills: "プログラミング不要・誰でも設定可（ブラウザから即利用）",
    costReductionPct: 35,
    timeReductionPct: 60,
    effectDescription: "市場調査・資料作成時間を最大60%削減。外部リサーチ費用の内製化や、提案資料作成の大幅時間短縮の事例が多い。",
    effectBaseline: "Genspark社ユーザー事例に基づく。市場調査・資料作成を外部リサーチ会社や担当者が行う場合の時間・外注費用を基準として算出。",
    selfSetupNote: "アカウント作成だけで即利用開始（費用なし）",
    fullDelegationNote: "リサーチ・資料作成の外部委託（コンサル・リサーチ会社）で¥100,000〜¥300,000程度/案件",
    selfMaintenanceNote: "特別な管理作業は不要、利用するだけ（月0〜1時間程度）",
    fullMaintenanceNote: "リサーチ業務の外部委託で¥100,000〜¥300,000/月程度",
    selfMaintenanceHoursPerMonth: 1,
    fullMaintenanceCostPerMonth: 300000,
    adminUserNote: "リサーチ・資料作成担当者：無料〜（利用回数制限あり、有料プランは要確認）",
    endUserNote: "作成した資料の閲覧者（一般ユーザー）：費用なし。Gensparkが生成した資料・レポートはURL共有で閲覧可能",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack"]),
  },
  {
    name: "Google Antigravity",
    company: "Google",
    logoEmoji: "🚀",
    websiteUrl: "https://antigravity.dev",
    description: "Googleが2025年11月に発表したAIエージェント型IDE。AIが計画・実装・動作確認まで自律的に実行。主に開発者向けだが、マークダウンで手順を書けば非エンジニアでも業務ワークフロー自動化・コンテンツ生成に活用できる。",
    features: JSON.stringify([
      "AIエージェントが計画→実装→検証を自律実行",
      "カスタム業務ワークフローの自動化ツール構築",
      "社内向けチャットボット・ツールの内製開発",
      "コンテンツ量産（1テーマ→複数バリエーション生成）",
      "ブラウザ操作・ターミナル実行の自動化",
      "Gemini 3・Claude・GPTなど複数モデルを選択可能",
    ]),
    categories: JSON.stringify(["chatbot", "docs", "sns"]),
    automationTags: JSON.stringify(["開発", "ワークフロー", "自動化", "ツール構築", "コンテンツ生成", "チャットボット構築", "内製化", "Gemini"]),
    freePlanAvailable: true,
    freePlanDescription: "個人プランは無料（パブリックプレビュー中）。Google One AI Proで拡張機能利用可",
    setupCost: "無料（Google アカウントで利用開始）",
    monthlyPriceFlat: 0,
    monthlyPriceLabel: "無料〜（チームはGoogle Workspace AIアドオンが必要）",
    enterpriseNote: "Organization プランはGoogle Cloud経由で提供予定（詳細未発表）",
    difficultyScore: 4,
    maintenanceScore: 3,
    requiredSkills: "エンジニア推奨（マークダウンで手順記述ができれば非エンジニアも試用可）",
    costReductionPct: 30,
    timeReductionPct: 50,
    effectDescription: "開発チームがある企業では内製ツール開発コストを大幅削減。非エンジニアでもワークフロー自動化・コンテンツ量産に活用できるが、習得コストは高め。",
    effectBaseline: "開発チーム・マーケ担当者の導入事例に基づく。AI活用前の開発・コンテンツ制作工数を基準として算出（ツール・スキルレベルにより変動幅大）。",
    selfSetupNote: "エンジニアがいれば社内対応可（工数20〜80時間）。外注の場合は¥200,000〜¥500,000程度",
    fullDelegationNote: "要件定義〜開発〜保守まで全て外注で¥500,000〜¥2,000,000程度（ツールの複雑さによって大幅変動）",
    selfMaintenanceNote: "エンジニアによる定期的な調整・改善が必要（月5〜15時間）",
    fullMaintenanceNote: "外部エンジニアの保守契約で¥50,000〜¥200,000/月程度",
    selfMaintenanceHoursPerMonth: 15,
    fullMaintenanceCostPerMonth: 200000,
    adminUserNote: "開発・構築担当者（エンジニア）：無料〜（Googleアカウントで利用開始）",
    endUserNote: "構築したツール・ボットの利用者：アクセス方法によって異なる。Web公開なら無料、社内システム連携の場合は別途インフラ費用が発生する可能性あり",
    endUserRequiresLicense: false,
    compatibleEnvs: JSON.stringify(["google"]),
  },
  {
    name: "n8n",
    company: "n8n GmbH",
    logoEmoji: "⚙️",
    websiteUrl: "https://n8n.io",
    description: "ノーコード/ローコードのワークフロー自動化プラットフォーム。AIノードを組み合わせて、チャットボット・メール自動返信・SNS自動投稿など、既製ツールでは実現できない独自の業務フローを視覚的に構築できる。",
    features: JSON.stringify([
      "AIノードによるLLM連携ワークフロー",
      "400種類以上のアプリ・サービスと連携",
      "チャットボット・自動返信フローの構築",
      "SNS・メール自動投稿スケジューリング",
      "セルフホストで社内データを安全に扱える",
      "トリガー設定による完全自動実行",
    ]),
    categories: JSON.stringify(["chatbot", "email", "docs", "sns"]),
    automationTags: JSON.stringify(["workflow", "automation", "ai", "integration"]),
    freePlanAvailable: true,
    setupCost: "セルフホスト：無料（サーバー費用のみ）／クラウド：無料プランあり",
    monthlyPriceFlat: 20000,
    monthlyPriceLabel: "セルフホスト：無料〜 ／ クラウド：約€20〜/月（約¥3,200〜）",
    enterpriseNote: "エンタープライズプランは要問合せ",
    difficultyScore: 3,
    maintenanceScore: 3,
    requiredSkills: "基本的なIT知識。セルフホストの場合はサーバー管理スキル推奨。ノーコードでフローを設計できるため非エンジニアでも習得可能",
    costReductionPct: 40,
    timeReductionPct: 60,
    effectDescription: "手作業の繰り返し業務を自動化し、複数ツールをつなぐオリジナルのAI業務フローを構築。既製ツールでは対応できない独自要件にも対応できる。",
    effectBaseline: "反復作業・ツール間の手動連携をゼロにした場合の工数削減効果を基準に算出",
    selfSetupNote: "社内でフロー設計・構築（工数15〜40時間）。セルフホストはサーバー準備が別途必要",
    fullDelegationNote: "フロー設計・構築・サーバー構築まで外注：¥150,000〜¥500,000程度",
    selfMaintenanceNote: "フローの追加・改修対応（月2〜8時間）",
    fullMaintenanceNote: "外部エンジニアによる保守：¥30,000〜¥100,000/月",
    selfMaintenanceHoursPerMonth: 5,
    fullMaintenanceCostPerMonth: 50000,
    adminUserNote: "フロー構築担当者：クラウド版は無料プランで開始可。セルフホストはサーバー費用のみ",
    endUserNote: "自動化フローの恩恵を受けるユーザー：追加費用なし（フロー経由で利用）",
    endUserRequiresLicense: false,
    isIncludedInEnv: null,
    relatedBaseEnv: null,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack", "notion", "salesforce"]),
  },
  {
    name: "Claude API（MCP対応）",
    company: "Anthropic",
    logoEmoji: "🔮",
    websiteUrl: "https://www.anthropic.com/api",
    description: "AnthropicのAI APIとMCP（Model Context Protocol）を使い、自社固有の業務に特化したオリジナルAIアプリを開発。社内DB・既存システム・外部ツールをAIに接続し、既製品では実現できない要件を完全カスタムで構築できる。",
    features: JSON.stringify([
      "自社業務に完全特化したAIアプリ開発",
      "MCPで社内システム・DBをAIに接続",
      "社内チャットボット・業務アシスタントの内製",
      "既存SaaSと連携したカスタムワークフロー",
      "データをすべて自社管理（セキュリティ強化）",
      "Claude最新モデルへの即日アップデート対応",
    ]),
    categories: JSON.stringify(["chatbot", "email", "docs", "sns"]),
    automationTags: JSON.stringify(["api", "custom", "mcp", "development"]),
    freePlanAvailable: false,
    setupCost: "開発費用：¥300,000〜（要件により変動）",
    monthlyPriceFlat: null,
    monthlyPricePerUser: null,
    monthlyPriceLabel: "API使用量課金（例：Claude Sonnet約$3/百万トークン）＋インフラ費用",
    enterpriseNote: "大規模・高トラフィック用途は要問合せ",
    difficultyScore: 5,
    maintenanceScore: 4,
    requiredSkills: "プログラミングスキル（Python / TypeScriptなど）、API設計・インフラ知識。社内エンジニアまたは外部開発パートナーが必要",
    costReductionPct: 50,
    timeReductionPct: 70,
    effectDescription: "完全カスタムのAI業務アプリで、既製ツールでは対応不可な独自フローを自動化。長期的に見ると月額SaaSよりコストを抑えられる場合もある。",
    effectBaseline: "既製SaaSの月額費用と比較した場合の試算。開発・保守コストを含めた総保有コストで評価すること",
    selfSetupNote: "社内エンジニアが開発・運用：APIコスト＋インフラ費用のみ（工数100〜300時間）",
    fullDelegationNote: "外部開発会社に委託：¥500,000〜¥3,000,000程度（要件・規模により大幅変動）",
    selfMaintenanceNote: "社内エンジニアによる継続改善・障害対応（月10〜20時間）",
    fullMaintenanceNote: "外部開発パートナーによる保守契約：¥80,000〜¥300,000/月",
    selfMaintenanceHoursPerMonth: 15,
    fullMaintenanceCostPerMonth: 150000,
    adminUserNote: "開発・運用担当エンジニア：APIキーで管理。使用量に応じた課金",
    endUserNote: "構築したアプリの利用者：追加のライセンス費用なし（APIコストは開発側が負担）",
    endUserRequiresLicense: false,
    isIncludedInEnv: null,
    relatedBaseEnv: null,
    compatibleEnvs: JSON.stringify(["google", "microsoft", "slack", "notion", "salesforce"]),
  },
];

async function main() {
  console.log("🌱 シードデータを投入中...");

  for (const tool of tools) {
    await prisma.tool.upsert({
      where: { name: tool.name },
      update: tool,
      create: tool,
    });
    console.log(`  ✅ ${tool.name}`);
  }

  console.log(`\n✨ ${tools.length}件のツールデータを投入しました`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
